# 服务端启动时的配置文件
[server]
address = "0.0.0.0:3000"
password = "pwd"

[log]
filter_level = "error"  # 可用的日志等级："debug", "info", "warn", "error"
with_ansi = false   # 有ansi字符美化控制台输出
to_stdout = false    # 输出到控制台，当打开时候不会写入到日志。在生产环境中应关闭
directory = "./logs"    # 日志目录
file_name = "deploy.log"  # 日志前缀
rolling = "daily"   # 可用的日志滚动策略："minutely", "hourly", "daily", "never"